export interface Tour {
  internalLinks?: Array<{ url: string; label: string }>
  metaTitle: string
  metaDescription?: string
  keywords?: string | string[]
  url: string
  id: string
  slug: string
  title: string
  description: string
  price: number
  currency: string
  rating: number
  reviewCount: number
  itinerary: string
  bookingUrl: string
  region: string
  country: string
}

export const pageKeywords: Tour[] = [
  {
    id: "kenya-masai-mara",
    slug: "masai-mara-luxury-safari",
    title: "Masai Mara Luxury Safari",
    description: "Experience the wildlife of Masai Mara with luxury accommodations and expert guides. Includes game drives and meals.",
    price: 3500,
    currency: "USD",
    rating: 4.8,
    reviewCount: 128,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Morning and evening game drives. Day 3: Optional hot air balloon ride and departure.",
    bookingUrl: "https://jaetravel.com/book/masai-mara-luxury-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Masai Mara Luxury Safari | Jae Travel",
    metaDescription: "Book your Masai Mara Luxury Safari with Jae Travel. Enjoy game drives, luxury lodges, and expert guides in Kenya's most iconic park.",
    keywords: ["Masai Mara Safari", "Luxury Kenya Safari", "Kenya Wildlife Tours"],
    url: "https://jaetravel.com/tours/masai-mara-luxury-safari",
  },
  {
    id: "kenya-amboseli",
    slug: "amboseli-safari",
    title: "Amboseli Safari Adventure",
    description: "Explore Amboseli National Park with guided game drives and spectacular views of Mount Kilimanjaro.",
    price: 2800,
    currency: "USD",
    rating: 4.7,
    reviewCount: 95,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Morning and evening game drives. Day 3: Departure.",
    bookingUrl: "https://jaetravel.com/book/amboseli-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Amboseli Safari Adventure | Jae Travel",
    metaDescription: "Discover Amboseli Safari with breathtaking views of Mount Kilimanjaro. Guided game drives and luxury stays included.",
    keywords: ["Amboseli Safari", "Kenya Tours", "Kilimanjaro Safari"],
    url: "https://jaetravel.com/tours/amboseli-safari",
  },
  {
    id: "tanzania-serengeti",
    slug: "serengeti-migration-tour",
    title: "Serengeti Migration Safari",
    description: "Witness the Great Migration in Serengeti with guided tours and comfortable lodges. Includes daily game drives and meals.",
    price: 4200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 97,
    itinerary: "Day 1: Arrival in Serengeti. Day 2-3: Game drives tracking the migration. Day 4: Cultural visit and departure.",
    bookingUrl: "https://jaetravel.com/book/serengeti-migration-tour",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Serengeti Migration Safari | Jae Travel",
    metaDescription: "Experience the Great Migration in Serengeti with expert guides, luxury lodges, and unforgettable wildlife encounters.",
    keywords: ["Serengeti Migration", "Tanzania Safari", "Great Migration Tour"],
    url: "https://jaetravel.com/tours/serengeti-migration-tour",
  },
  {
    id: "tanzania-ngorongoro",
    slug: "ngorongoro-crater-safari",
    title: "Ngorongoro Crater Safari",
    description: "Explore the Ngorongoro Crater with guided game drives and luxury accommodation. Ideal for families and photographers.",
    price: 2800,
    currency: "USD",
    rating: 4.7,
    reviewCount: 64,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Full-day game drive in the crater. Day 3: Departure.",
    bookingUrl: "https://jaetravel.com/book/ngorongoro-crater-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Ngorongoro Crater Safari | Jae Travel",
    metaDescription: "Book your Ngorongoro Crater Safari with Jae Travel. A perfect adventure for families, photographers, and nature lovers.",
    keywords: ["Ngorongoro Safari", "Tanzania Wildlife Tours", "Family Safari"],
    url: "https://jaetravel.com/tours/ngorongoro-crater-safari",
  },
  {
    id: "uganda-bwindi",
    slug: "bwindi-gorilla-trek",
    title: "Bwindi Gorilla Trekking",
    description: "Trek the dense forests of Bwindi to see mountain gorillas up close with expert guides. Includes park fees and accommodations.",
    price: 3200,
    currency: "USD",
    rating: 4.8,
    reviewCount: 80,
    itinerary: "Day 1: Arrival at lodge. Day 2: Gorilla trekking experience. Day 3: Cultural visit and departure.",
    bookingUrl: "https://jaetravel.com/book/bwindi-gorilla-trek",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Bwindi Gorilla Trekking | Jae Travel",
    metaDescription: "Embark on a Bwindi Gorilla Trekking safari. See mountain gorillas up close and explore Uganda's lush forests.",
    keywords: ["Bwindi Gorilla Trek", "Uganda Safari", "Gorilla Trekking Tours"],
    url: "https://jaetravel.com/tours/bwindi-gorilla-trek",
  },
  {
    id: "rwanda-volcanoes",
    slug: "volcanoes-national-park-safari",
    title: "Rwanda Gorilla Safari",
    description: "Explore Volcanoes National Park in Rwanda to trek gorillas and experience local culture.",
    price: 3800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 72,
    itinerary: "Day 1: Arrival and lodge check-in. Day 2: Gorilla trekking. Day 3: Cultural tour and departure.",
    bookingUrl: "https://jaetravel.com/book/volcanoes-national-park-safari",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Rwanda Gorilla Safari | Jae Travel",
    metaDescription: "Book your Rwanda Gorilla Safari in Volcanoes National Park. Trek gorillas, enjoy cultural tours, and luxury accommodations.",
    keywords: ["Rwanda Gorilla Safari", "Volcanoes National Park", "Gorilla Trekking Rwanda"],
    url: "https://jaetravel.com/tours/volcanoes-national-park-safari",
  },
  // Kenya Tours
  {
    id: "1",
    slug: "masai-mara-safari-adventure",
    title: "Masai Mara JaeTravel Expeditions",
    description: "Experience the great migration and witness the Big Five.",
    price: 1200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "5-day safari in Masai Mara with game drives and wildlife viewing",
    bookingUrl: "https://jaetravel.com/book/masai-mara-safari-adventure",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Masai Mara Safari Adventure | Jae Travel",
    metaDescription: "Experience the great migration and witness the Big Five in Masai Mara with Jae Travel Expeditions.",
    keywords: ["Masai Mara", "Kenya Safari", "Big Five", "Great Migration"],
    url: "https://jaetravel.com/tours/masai-mara-safari-adventure",
  },
  {
    id: "2",
    slug: "amboseli-elephant-safari",
    title: "Amboseli Elephant Safari",
    description: "Get close to elephants with Mount Kilimanjaro backdrop.",
    price: 980,
    currency: "USD",
    rating: 4.7,
    reviewCount: 0,
    itinerary: "4-day safari in Amboseli National Park with elephant viewing",
    bookingUrl: "https://jaetravel.com/book/amboseli-elephant-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Amboseli Elephant Safari | Jae Travel",
    metaDescription: "Get close to elephants with Mount Kilimanjaro backdrop on this Amboseli Elephant Safari.",
    keywords: ["Amboseli", "Elephant Safari", "Kilimanjaro"],
    url: "https://jaetravel.com/tours/amboseli-elephant-safari",
  },
  {
    id: "3",
    slug: "samburu-game-reserve",
    title: "Samburu Game Reserve",
    description: "Discover unique wildlife in the northern frontier.",
    price: 750,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "3-day safari in Samburu Game Reserve",
    bookingUrl: "https://jaetravel.com/book/samburu-game-reserve",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Samburu Game Reserve Safari | Jae Travel",
    metaDescription: "Discover unique wildlife in the northern frontier of Kenya at Samburu Game Reserve.",
    keywords: ["Samburu", "Game Reserve", "Northern Kenya"],
    url: "https://jaetravel.com/tours/samburu-game-reserve",
  },
  {
    id: "4",
    slug: "lake-nakuru-flamingo-spectacle",
    title: "Lake Nakuru Flamingo Tour",
    description: "Witness thousands of flamingos in their natural habitat.",
    price: 450,
    currency: "USD",
    rating: 4.5,
    reviewCount: 0,
    itinerary: "2-day tour to Lake Nakuru for flamingo viewing",
    bookingUrl: "https://jaetravel.com/book/lake-nakuru-flamingo-spectacle",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Lake Nakuru Flamingo Tour | Jae Travel",
    metaDescription: "Witness thousands of flamingos in their natural habitat at Lake Nakuru.",
    keywords: ["Lake Nakuru", "Flamingos", "Bird Watching"],
    url: "https://jaetravel.com/tours/lake-nakuru-flamingo-spectacle",
  },
  {
    id: "5",
    slug: "tsavo-east-west-adventure",
    title: "Tsavo East & West Safari",
    description: "Explore Kenya's largest national park.",
    price: 1350,
    currency: "USD",
    rating: 4.8,
    reviewCount: 0,
    itinerary: "6-day safari exploring both Tsavo East and Tsavo West National Parks",
    bookingUrl: "https://jaetravel.com/book/tsavo-east-west-adventure",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Tsavo East & West Safari | Jae Travel",
    metaDescription: "Explore Kenya's largest national park with our Tsavo East & West Safari.",
    keywords: ["Tsavo", "National Park", "Kenya Safari"],
    url: "https://jaetravel.com/tours/tsavo-east-west-adventure",
  },
  {
    id: "6",
    slug: "mombasa-coastal-safari",
    title: "Mombasa Beach & Safari",
    description: "Combine JaeTravel Expeditions with beach relaxation.",
    price: 1600,
    currency: "USD",
    rating: 4.7,
    reviewCount: 0,
    itinerary: "7-day combination safari and beach holiday in Mombasa",
    bookingUrl: "https://jaetravel.com/book/mombasa-coastal-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Mombasa Beach & Safari | Jae Travel",
    metaDescription: "Combine safari adventures with beach relaxation on our Mombasa Beach & Safari package.",
    keywords: ["Mombasa", "Beach Safari", "Coastal Kenya"],
    url: "https://jaetravel.com/tours/mombasa-coastal-safari",
  },
  {
    id: "7",
    slug: "mount-kenya-climbing-Expeditions",
    title: "Mount Kenya Climbing",
    description: "Challenge yourself with Africa's second highest peak.",
    price: 1100,
    currency: "USD",
    rating: 4.4,
    reviewCount: 0,
    itinerary: "5-day climbing expedition to Mount Kenya",
    bookingUrl: "https://jaetravel.com/book/mount-kenya-climbing-Expeditions",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Mount Kenya Climbing Expedition | Jae Travel",
    metaDescription: "Challenge yourself with Africa's second highest peak on our Mount Kenya climbing expedition.",
    keywords: ["Mount Kenya", "Climbing", "Trekking"],
    url: "https://jaetravel.com/tours/mount-kenya-climbing-Expeditions",
  },
  {
    id: "8",
    slug: "laikipia-conservancy",
    title: "Laikipia Conservancy",
    description: "Experience conservation in action.",
    price: 1250,
    currency: "USD",
    rating: 4.8,
    reviewCount: 0,
    itinerary: "4-day conservation experience in Laikipia Conservancy",
    bookingUrl: "https://jaetravel.com/book/laikipia-conservancy",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Laikipia Conservancy Experience | Jae Travel",
    metaDescription: "Experience conservation in action at Laikipia Conservancy.",
    keywords: ["Laikipia", "Conservancy", "Conservation"],
    url: "https://jaetravel.com/tours/laikipia-conservancy",
  },
  {
    id: "9",
    slug: "hell-gate-lake-naivasha-adventure",
    title: "Hell's Gate Adventure",
    description: "Bike and hike through dramatic landscapes.",
    price: 380,
    currency: "USD",
    rating: 4.3,
    reviewCount: 0,
    itinerary: "2-day adventure tour of Hell's Gate and Lake Naivasha",
    bookingUrl: "https://jaetravel.com/book/hell-gate-lake-naivasha-adventure",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Hell's Gate Adventure Tour | Jae Travel",
    metaDescription: "Bike and hike through dramatic landscapes at Hell's Gate National Park.",
    keywords: ["Hell's Gate", "Adventure", "Biking"],
    url: "https://jaetravel.com/tours/hell-gate-lake-naivasha-adventure",
  },
  {
    id: "10",
    slug: "maasai-cultural-experience",
    title: "Maasai Cultural Experience",
    description: "Immerse yourself in Maasai culture.",
    price: 650,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "3-day cultural immersion with the Maasai people",
    bookingUrl: "https://jaetravel.com/book/maasai-cultural-experience",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Maasai Cultural Experience | Jae Travel",
    metaDescription: "Immerse yourself in Maasai culture with our authentic cultural experience.",
    keywords: ["Maasai", "Cultural Experience", "Kenya Culture"],
    url: "https://jaetravel.com/tours/maasai-cultural-experience",
  },
  {
    id: "11",
    slug: "aberdare-national-park-safari",
    title: "Aberdare National Park",
    description: "Mountain forest safari experience.",
    price: 720,
    currency: "USD",
    rating: 4.5,
    reviewCount: 0,
    itinerary: "3-day safari in Aberdare National Park",
    bookingUrl: "https://jaetravel.com/book/aberdare-national-park-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Aberdare National Park Safari | Jae Travel",
    metaDescription: "Experience a mountain forest safari in Aberdare National Park.",
    keywords: ["Aberdare", "National Park", "Mountain Safari"],
    url: "https://jaetravel.com/tours/aberdare-national-park-safari",
  },
  {
    id: "12",
    slug: "diani-beach-safari-combo",
    title: "Diani Beach Safari Combo",
    description: "Ultimate Kenya safari and beach experience.",
    price: 1800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "8-day combination safari and beach holiday at Diani Beach",
    bookingUrl: "https://jaetravel.com/book/diani-beach-safari-combo",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Diani Beach Safari Combo | Jae Travel",
    metaDescription: "Experience the ultimate Kenya safari and beach experience at Diani Beach.",
    keywords: ["Diani Beach", "Beach Safari", "Kenya Coast"],
    url: "https://jaetravel.com/tours/diani-beach-safari-combo",
  },
  // Tanzania Tours
  {
    id: "13",
    slug: "serengeti-wildlife-safari",
    title: "Serengeti Wildlife Safari",
    description: "Explore the endless plains of Serengeti.",
    price: 1800,
    currency: "USD",
    rating: 4.8,
    reviewCount: 0,
    itinerary: "7-day safari in Serengeti National Park",
    bookingUrl: "https://jaetravel.com/book/serengeti-wildlife-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Serengeti Wildlife Safari | Jae Travel",
    metaDescription: "Explore the endless plains of Serengeti on our wildlife safari.",
    keywords: ["Serengeti", "Wildlife Safari", "Tanzania"],
    url: "https://jaetravel.com/tours/serengeti-wildlife-safari",
  },
  {
    id: "14",
    slug: "ngorongoro-crater-safari",
    title: "Ngorongoro Crater Tour",
    description: "Visit the world's largest intact caldera.",
    price: 950,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "3-day tour of Ngorongoro Crater",
    bookingUrl: "https://jaetravel.com/book/ngorongoro-crater-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Ngorongoro Crater Tour | Jae Travel",
    metaDescription: "Visit the world's largest intact caldera at Ngorongoro Crater.",
    keywords: ["Ngorongoro", "Crater", "Caldera"],
    url: "https://jaetravel.com/tours/ngorongoro-crater-safari",
  },
  {
    id: "15",
    slug: "kilimanjaro-climbing-Expeditions",
    title: "Kilimanjaro Climbing",
    description: "Conquer Africa's highest peak.",
    price: 2200,
    currency: "USD",
    rating: 4.7,
    reviewCount: 0,
    itinerary: "8-day climbing expedition to Mount Kilimanjaro",
    bookingUrl: "https://jaetravel.com/book/kilimanjaro-climbing-Expeditions",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Kilimanjaro Climbing Expedition | Jae Travel",
    metaDescription: "Conquer Africa's highest peak on our Mount Kilimanjaro climbing expedition.",
    keywords: ["Kilimanjaro", "Climbing", "Trekking"],
    url: "https://jaetravel.com/tours/kilimanjaro-climbing-Expeditions",
  },
  {
    id: "16",
    slug: "tarangire-national-park-safari",
    title: "Tarangire Elephant Safari",
    description: "See large herds of elephants.",
    price: 1100,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "4-day safari in Tarangire National Park focusing on elephants",
    bookingUrl: "https://jaetravel.com/book/tarangire-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Tarangire Elephant Safari | Jae Travel",
    metaDescription: "See large herds of elephants in Tarangire National Park.",
    keywords: ["Tarangire", "Elephant Safari", "Tanzania"],
    url: "https://jaetravel.com/tours/tarangire-national-park-safari",
  },
  {
    id: "17",
    slug: "lake-manyara-national-park-safari",
    title: "Lake Manyara Tree Climbing Lions",
    description: "Witness unique tree-climbing lions.",
    price: 580,
    currency: "USD",
    rating: 4.4,
    reviewCount: 0,
    itinerary: "2-day safari in Lake Manyara National Park",
    bookingUrl: "https://jaetravel.com/book/lake-manyara-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Lake Manyara Tree Climbing Lions Safari | Jae Travel",
    metaDescription: "Witness unique tree-climbing lions in Lake Manyara National Park.",
    keywords: ["Lake Manyara", "Tree Climbing Lions", "Tanzania Safari"],
    url: "https://jaetravel.com/tours/lake-manyara-national-park-safari",
  },
  {
    id: "18",
    slug: "zanzibar-beach-holiday",
    title: "Zanzibar Spice Island",
    description: "Explore the spice island paradise.",
    price: 1300,
    currency: "USD",
    rating: 4.8,
    reviewCount: 0,
    itinerary: "5-day beach holiday in Zanzibar",
    bookingUrl: "https://jaetravel.com/book/zanzibar-beach-holiday",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Zanzibar Spice Island Holiday | Jae Travel",
    metaDescription: "Explore the spice island paradise of Zanzibar.",
    keywords: ["Zanzibar", "Spice Island", "Beach Holiday"],
    url: "https://jaetravel.com/tours/zanzibar-beach-holiday",
  },
  {
    id: "19",
    slug: "ruaha-national-park-safari",
    title: "Ruaha National Park",
    description: "Tanzania's largest national park.",
    price: 1450,
    currency: "USD",
    rating: 4.5,
    reviewCount: 0,
    itinerary: "6-day safari in Ruaha National Park",
    bookingUrl: "https://jaetravel.com/book/ruaha-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Ruaha National Park Safari | Jae Travel",
    metaDescription: "Explore Tanzania's largest national park at Ruaha.",
    keywords: ["Ruaha", "National Park", "Tanzania Safari"],
    url: "https://jaetravel.com/tours/ruaha-national-park-safari",
  },
  {
    id: "20",
    slug: "selous-game-reserve-safari",
    title: "Selous Game Reserve",
    description: "Africa's largest game reserve.",
    price: 1350,
    currency: "USD",
    rating: 4.7,
    reviewCount: 0,
    itinerary: "5-day safari in Selous Game Reserve",
    bookingUrl: "https://jaetravel.com/book/selous-game-reserve-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Selous Game Reserve Safari | Jae Travel",
    metaDescription: "Explore Africa's largest game reserve at Selous.",
    keywords: ["Selous", "Game Reserve", "Tanzania"],
    url: "https://jaetravel.com/tours/selous-game-reserve-safari",
  },
  {
    id: "21",
    slug: "mikumi-national-park",
    title: "Mikumi National Park",
    description: "Accessible wildlife viewing.",
    price: 750,
    currency: "USD",
    rating: 4.3,
    reviewCount: 0,
    itinerary: "3-day safari in Mikumi National Park",
    bookingUrl: "https://jaetravel.com/book/mikumi-national-park",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Mikumi National Park Safari | Jae Travel",
    metaDescription: "Enjoy accessible wildlife viewing in Mikumi National Park.",
    keywords: ["Mikumi", "National Park", "Wildlife Viewing"],
    url: "https://jaetravel.com/tours/mikumi-national-park",
  },
  {
    id: "22",
    slug: "arusha-cultural-tour",
    title: "Arusha Cultural Tour",
    description: "Experience local Tanzanian culture.",
    price: 420,
    currency: "USD",
    rating: 4.2,
    reviewCount: 0,
    itinerary: "2-day cultural tour in Arusha",
    bookingUrl: "https://jaetravel.com/book/arusha-cultural-tour",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Arusha Cultural Tour | Jae Travel",
    metaDescription: "Experience local Tanzanian culture in Arusha.",
    keywords: ["Arusha", "Cultural Tour", "Tanzania Culture"],
    url: "https://jaetravel.com/tours/arusha-cultural-tour",
  },
  {
    id: "23",
    slug: "katavi-national-park-safari",
    title: "Katavi National Park",
    description: "Remote wilderness experience.",
    price: 1600,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "4-day safari in remote Katavi National Park",
    bookingUrl: "https://jaetravel.com/book/katavi-national-park-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Katavi National Park Safari | Jae Travel",
    metaDescription: "Experience remote wilderness in Katavi National Park.",
    keywords: ["Katavi", "National Park", "Wilderness"],
    url: "https://jaetravel.com/tours/katavi-national-park-safari",
  },
  {
    id: "24",
    slug: "mahale-mountains-national-park-chimpanzee-trekking",
    title: "Mahale Chimpanzee Trek",
    description: "Trek with wild chimpanzees.",
    price: 2100,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "6-day chimpanzee trekking in Mahale Mountains National Park",
    bookingUrl: "https://jaetravel.com/book/mahale-mountains-national-park-chimpanzee-trekking",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Mahale Chimpanzee Trek | Jae Travel",
    metaDescription: "Trek with wild chimpanzees in Mahale Mountains National Park.",
    keywords: ["Mahale", "Chimpanzee Trek", "Tanzania"],
    url: "https://jaetravel.com/tours/mahale-mountains-national-park-chimpanzee-trekking",
  },
  {
    id: "25",
    slug: "pemba-island-diving",
    title: "Pemba Island Diving",
    description: "World-class diving experience.",
    price: 980,
    currency: "USD",
    rating: 4.5,
    reviewCount: 0,
    itinerary: "4-day diving experience in Pemba Island",
    bookingUrl: "https://jaetravel.com/book/pemba-island-diving",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Pemba Island Diving | Jae Travel",
    metaDescription: "Experience world-class diving in Pemba Island.",
    keywords: ["Pemba Island", "Diving", "Scuba Diving"],
    url: "https://jaetravel.com/tours/pemba-island-diving",
  },
  {
    id: "26",
    slug: "stone-town-heritage-tour",
    title: "Stone Town Heritage Tour",
    description: "Explore UNESCO World Heritage site.",
    price: 350,
    currency: "USD",
    rating: 4.4,
    reviewCount: 0,
    itinerary: "2-day heritage tour of Stone Town",
    bookingUrl: "https://jaetravel.com/book/stone-town-heritage-tour",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Stone Town Heritage Tour | Jae Travel",
    metaDescription: "Explore UNESCO World Heritage site in Stone Town, Zanzibar.",
    keywords: ["Stone Town", "Heritage Tour", "UNESCO"],
    url: "https://jaetravel.com/tours/stone-town-heritage-tour",
  },
  {
    id: "27",
    slug: "northern-circuit-safari",
    title: "Northern Circuit Safari",
    description: "Complete northern Tanzania experience.",
    price: 2800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "10-day comprehensive safari of northern Tanzania",
    bookingUrl: "https://jaetravel.com/book/northern-circuit-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Northern Circuit Safari | Jae Travel",
    metaDescription: "Experience the complete northern Tanzania safari circuit.",
    keywords: ["Northern Circuit", "Tanzania Safari", "Comprehensive Safari"],
    url: "https://jaetravel.com/tours/northern-circuit-safari",
  },
  // Rwanda Tours
  {
    id: "28",
    slug: "gorilla-trekking-experience",
    title: "Gorilla Trekking Experience",
    description: "Get up close with mountain gorillas.",
    price: 2500,
    currency: "USD",
    rating: 5.0,
    reviewCount: 0,
    itinerary: "3-day gorilla trekking experience in Rwanda",
    bookingUrl: "https://jaetravel.com/book/gorilla-trekking-experience",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Gorilla Trekking Experience | Jae Travel",
    metaDescription: "Get up close with mountain gorillas in Rwanda.",
    keywords: ["Gorilla Trekking", "Rwanda", "Mountain Gorillas"],
    url: "https://jaetravel.com/tours/gorilla-trekking-experience",
  },
  {
    id: "29",
    slug: "nyungwe-forest-canopy-walk",
    title: "Nyungwe Forest Canopy Walk",
    description: "Walk among the treetops.",
    price: 450,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "2-day canopy walk experience in Nyungwe Forest",
    bookingUrl: "https://jaetravel.com/book/nyungwe-forest-canopy-walk",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Nyungwe Forest Canopy Walk | Jae Travel",
    metaDescription: "Walk among the treetops in Nyungwe Forest, Rwanda.",
    keywords: ["Nyungwe Forest", "Canopy Walk", "Rwanda"],
    url: "https://jaetravel.com/tours/nyungwe-forest-canopy-walk",
  },
  {
    id: "30",
    slug: "lake-kivu-relaxation",
    title: "Lake Kivu Relaxation",
    description: "Relax by Africa's great lake.",
    price: 380,
    currency: "USD",
    rating: 4.4,
    reviewCount: 0,
    itinerary: "3-day relaxation tour at Lake Kivu",
    bookingUrl: "https://jaetravel.com/book/lake-kivu-relaxation",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Lake Kivu Relaxation | Jae Travel",
    metaDescription: "Relax by Africa's great lake at Lake Kivu, Rwanda.",
    keywords: ["Lake Kivu", "Relaxation", "Rwanda"],
    url: "https://jaetravel.com/tours/lake-kivu-relaxation",
  },
  {
    id: "31",
    slug: "akagera-national-park-safari",
    title: "Akagera National Park",
    description: "Rwanda's only savanna park.",
    price: 520,
    currency: "USD",
    rating: 4.5,
    reviewCount: 0,
    itinerary: "2-day safari in Akagera National Park",
    bookingUrl: "https://jaetravel.com/book/akagera-national-park-safari",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Akagera National Park Safari | Jae Travel",
    metaDescription: "Explore Rwanda's only savanna park at Akagera National Park.",
    keywords: ["Akagera", "National Park", "Rwanda Safari"],
    url: "https://jaetravel.com/tours/akagera-national-park-safari",
  },
  {
    id: "32",
    slug: "kigali-city-tour",
    title: "Kigali City Tour",
    description: "Explore the clean city of Kigali.",
    price: 150,
    currency: "USD",
    rating: 4.3,
    reviewCount: 0,
    itinerary: "1-day city tour of Kigali",
    bookingUrl: "https://jaetravel.com/book/kigali-city-tour",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Kigali City Tour | Jae Travel",
    metaDescription: "Explore the clean city of Kigali, Rwanda.",
    keywords: ["Kigali", "City Tour", "Rwanda"],
    url: "https://jaetravel.com/tours/kigali-city-tour",
  },
  {
    id: "33",
    slug: "golden-monkey-tracking",
    title: "Golden Monkey Tracking",
    description: "Track rare golden monkeys.",
    price: 680,
    currency: "USD",
    rating: 4.7,
    reviewCount: 0,
    itinerary: "2-day golden monkey tracking experience",
    bookingUrl: "https://jaetravel.com/book/golden-monkey-tracking",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Golden Monkey Tracking | Jae Travel",
    metaDescription: "Track rare golden monkeys in Rwanda.",
    keywords: ["Golden Monkey", "Tracking", "Rwanda"],
    url: "https://jaetravel.com/tours/golden-monkey-tracking",
  },
  // Uganda Tours
  {
    id: "34",
    slug: "bwindi-gorilla-trekking",
    title: "Bwindi Gorilla Trekking",
    description: "Trek mountain gorillas in Bwindi.",
    price: 2200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "4-day gorilla trekking in Bwindi Impenetrable Forest",
    bookingUrl: "https://jaetravel.com/book/bwindi-gorilla-trekking",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Bwindi Gorilla Trekking | Jae Travel",
    metaDescription: "Trek mountain gorillas in Bwindi Impenetrable Forest, Uganda.",
    keywords: ["Bwindi", "Gorilla Trekking", "Uganda"],
    url: "https://jaetravel.com/tours/bwindi-gorilla-trekking",
  },
  {
    id: "35",
    slug: "queen-elizabeth-national-park-safari",
    title: "Queen Elizabeth Safari",
    description: "Diverse wildlife in scenic landscapes.",
    price: 1150,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "5-day safari in Queen Elizabeth National Park",
    bookingUrl: "https://jaetravel.com/book/queen-elizabeth-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Queen Elizabeth Safari | Jae Travel",
    metaDescription: "Experience diverse wildlife in scenic landscapes at Queen Elizabeth National Park, Uganda.",
    keywords: ["Queen Elizabeth", "National Park", "Uganda Safari"],
    url: "https://jaetravel.com/tours/queen-elizabeth-national-park-safari",
  },
  {
    id: "36",
    slug: "murchison-falls-national-park-safari",
    title: "Murchison Falls Adventure",
    description: "Witness the powerful Murchison Falls.",
    price: 980,
    currency: "USD",
    rating: 4.7,
    reviewCount: 0,
    itinerary: "4-day adventure tour to Murchison Falls National Park",
    bookingUrl: "https://jaetravel.com/book/murchison-falls-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Murchison Falls Adventure | Jae Travel",
    metaDescription: "Witness the powerful Murchison Falls in Uganda.",
    keywords: ["Murchison Falls", "Adventure", "Uganda"],
    url: "https://jaetravel.com/tours/murchison-falls-national-park-safari",
  },
  {
    id: "37",
    slug: "kibale-national-park-chimpanzee-trekking",
    title: "Kibale Chimpanzee Tracking",
    description: "Track our closest relatives.",
    price: 750,
    currency: "USD",
    rating: 4.5,
    reviewCount: 0,
    itinerary: "3-day chimpanzee tracking in Kibale National Park",
    bookingUrl: "https://jaetravel.com/book/kibale-national-park-chimpanzee-trekking",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Kibale Chimpanzee Tracking | Jae Travel",
    metaDescription: "Track our closest relatives in Kibale National Park, Uganda.",
    keywords: ["Kibale", "Chimpanzee Tracking", "Uganda"],
    url: "https://jaetravel.com/tours/kibale-national-park-chimpanzee-trekking",
  },
  {
    id: "38",
    slug: "lake-mburo-national-park-safari",
    title: "Lake Mburo National Park",
    description: "Compact park with diverse wildlife.",
    price: 420,
    currency: "USD",
    rating: 4.3,
    reviewCount: 0,
    itinerary: "2-day safari in Lake Mburo National Park",
    bookingUrl: "https://jaetravel.com/book/lake-mburo-national-park-safari",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Lake Mburo National Park Safari | Jae Travel",
    metaDescription: "Explore a compact park with diverse wildlife at Lake Mburo National Park, Uganda.",
    keywords: ["Lake Mburo", "National Park", "Uganda Safari"],
    url: "https://jaetravel.com/tours/lake-mburo-national-park-safari",
  },
  {
    id: "39",
    slug: "rwenzori-mountains-hiking",
    title: "Rwenzori Mountains Hiking",
    description: "Hike the Mountains of the Moon.",
    price: 1800,
    currency: "USD",
    rating: 4.8,
    reviewCount: 0,
    itinerary: "7-day hiking expedition in Rwenzori Mountains",
    bookingUrl: "https://jaetravel.com/book/rwenzori-mountains-hiking",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Rwenzori Mountains Hiking | Jae Travel",
    metaDescription: "Hike the Mountains of the Moon in Rwenzori Mountains, Uganda.",
    keywords: ["Rwenzori", "Mountains", "Hiking"],
    url: "https://jaetravel.com/tours/rwenzori-mountains-hiking",
  },
  {
    id: "40",
    slug: "jinja-adventure-tour",
    title: "Jinja White Water Rafting",
    description: "Adventure at the source of the Nile.",
    price: 350,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "2-day adventure tour in Jinja with white water rafting",
    bookingUrl: "https://jaetravel.com/book/jinja-adventure-tour",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Jinja White Water Rafting | Jae Travel",
    metaDescription: "Experience adventure at the source of the Nile in Jinja, Uganda.",
    keywords: ["Jinja", "White Water Rafting", "Nile River"],
    url: "https://jaetravel.com/tours/jinja-adventure-tour",
  },
  {
    id: "41",
    slug: "lake-bunyonyi-relaxation-tour",
    title: "Lake Bunyonyi Relaxation",
    description: "Relax by Uganda's deepest lake.",
    price: 450,
    currency: "USD",
    rating: 4.4,
    reviewCount: 0,
    itinerary: "3-day relaxation tour at Lake Bunyonyi",
    bookingUrl: "https://jaetravel.com/book/lake-bunyonyi-relaxation-tour",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Lake Bunyonyi Relaxation | Jae Travel",
    metaDescription: "Relax by Uganda's deepest lake at Lake Bunyonyi.",
    keywords: ["Lake Bunyonyi", "Relaxation", "Uganda"],
    url: "https://jaetravel.com/tours/lake-bunyonyi-relaxation-tour",
  },
  {
    id: "42",
    slug: "ssese-islands-beach-holiday",
    title: "Ssese Islands Beach Holiday",
    description: "Beach paradise on Lake Victoria.",
    price: 650,
    currency: "USD",
    rating: 4.5,
    reviewCount: 0,
    itinerary: "4-day beach holiday on Ssese Islands",
    bookingUrl: "https://jaetravel.com/book/ssese-islands-beach-holiday",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Ssese Islands Beach Holiday | Jae Travel",
    metaDescription: "Experience beach paradise on Lake Victoria at Ssese Islands, Uganda.",
    keywords: ["Ssese Islands", "Beach Holiday", "Lake Victoria"],
    url: "https://jaetravel.com/tours/ssese-islands-beach-holiday",
  },
  {
    id: "43",
    slug: "lake-naivasha-boat-safari",
    title: "Lake Naivasha Boat Safari",
    description: "Boat safari on freshwater Lake Naivasha with hippos, birds, and Crescent Island walking safari.",
    price: 150,
    currency: "USD",
    rating: 4.3,
    reviewCount: 0,
    itinerary: "1-day boat safari on Lake Naivasha",
    bookingUrl: "https://jaetravel.com/book/lake-naivasha-boat-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Lake Naivasha Boat Safari | Jae Travel",
    metaDescription: "Enjoy a boat safari on freshwater Lake Naivasha with hippos, birds, and Crescent Island walking safari.",
    keywords: ["Lake Naivasha", "Boat Safari", "Kenya"],
    url: "https://jaetravel.com/tours/lake-naivasha-boat-safari",
  },
  {
    id: "44",
    slug: "kenya-disability-safari",
    title: "Accessible Kenya Safari Experience for people with disabilities",
    description: "A fully accessible safari experience designed for travelers with mobility challenges, featuring wheelchair-accessible vehicles, accommodations, and tailored wildlife viewing.",
    price: 2450,
    currency: "USD",
    rating: 4.8,
    reviewCount: 0,
    itinerary: "7-day accessible safari experience in Kenya",
    bookingUrl: "https://jaetravel.com/book/kenya-disability-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Accessible Kenya Safari Experience | Jae Travel",
    metaDescription: "A fully accessible safari experience designed for travelers with mobility challenges in Kenya.",
    keywords: ["Accessible Safari", "Disability Travel", "Kenya"],
    url: "https://jaetravel.com/tours/kenya-disability-safari",
  },
  {
    id: "45",
    slug: "accessible-masai-mara-safari",
    title: "4-Day Accessible Masai Mara Experience",
    description: "A focused accessible safari in the Masai Mara with wheelchair-adapted vehicles, accessible tented camps, and front-row seats to the Great Migration.",
    price: 1450,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "4-day accessible safari in Masai Mara",
    bookingUrl: "https://jaetravel.com/book/accessible-masai-mara-safari",
    region: "East Africa",
    country: "Kenya",
    metaTitle: "Accessible Masai Mara Experience | Jae Travel",
    metaDescription: "A focused accessible safari in the Masai Mara with wheelchair-adapted vehicles and accessible tented camps.",
    keywords: ["Accessible Masai Mara", "Disability Safari", "Kenya"],
    url: "https://jaetravel.com/tours/accessible-masai-mara-safari",
  },
  {
    id: "46",
    slug: "tanzania-accessible-safari",
    title: "Tanzania Accessible Safari Adventure",
    description: "An inclusive journey through Tanzania's Serengeti and Ngorongoro Crater with adapted safari vehicles, accessible lodges, and unforgettable wildlife encounters.",
    price: 2950,
    currency: "USD",
    rating: 4.7,
    reviewCount: 0,
    itinerary: "8-day accessible safari in Tanzania",
    bookingUrl: "https://jaetravel.com/book/tanzania-accessible-safari",
    region: "East Africa",
    country: "Tanzania",
    metaTitle: "Tanzania Accessible Safari Adventure | Jae Travel",
    metaDescription: "An inclusive journey through Tanzania's Serengeti and Ngorongoro Crater with adapted safari vehicles and accessible lodges.",
    keywords: ["Accessible Tanzania Safari", "Disability Travel", "Tanzania"],
    url: "https://jaetravel.com/tours/tanzania-accessible-safari",
  },
  {
    id: "47",
    slug: "rwanda-accessible-gorilla-safari",
    title: "Rwanda Accessible Gorilla Experience",
    description: "A rare opportunity to experience Rwanda's mountain gorillas with specially designed accessible trekking routes, adapted viewing platforms, and cultural encounters.",
    price: 3200,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "5-day accessible gorilla experience in Rwanda",
    bookingUrl: "https://jaetravel.com/book/rwanda-accessible-gorilla-safari",
    region: "East Africa",
    country: "Rwanda",
    metaTitle: "Rwanda Accessible Gorilla Experience | Jae Travel",
    metaDescription: "A rare opportunity to experience Rwanda's mountain gorillas with specially designed accessible trekking routes.",
    keywords: ["Accessible Gorilla Trekking", "Rwanda", "Disability Travel"],
    url: "https://jaetravel.com/tours/rwanda-accessible-gorilla-safari",
  },
  {
    id: "48",
    slug: "uganda-accessible-primate-safari",
    title: "Uganda Accessible Primate Safari",
    description: "An accessible primate-focused safari in Uganda with wheelchair-friendly pathways, adapted chimpanzee and gorilla viewing, and a Kazinga Channel boat safari.",
    price: 2200,
    currency: "USD",
    rating: 4.6,
    reviewCount: 0,
    itinerary: "6-day accessible primate safari in Uganda",
    bookingUrl: "https://jaetravel.com/book/uganda-accessible-primate-safari",
    region: "East Africa",
    country: "Uganda",
    metaTitle: "Uganda Accessible Primate Safari | Jae Travel",
    metaDescription: "An accessible primate-focused safari in Uganda with wheelchair-friendly pathways and adapted chimpanzee and gorilla viewing.",
    keywords: ["Accessible Primate Safari", "Uganda", "Disability Travel"],
    url: "https://jaetravel.com/tours/uganda-accessible-primate-safari",
  },
  {
    id: "49",
    slug: "east-africa-grand-accessible-safari",
    title: "East Africa Grand Accessible Safari",
    description: "The ultimate East African accessible safari across Kenya and Tanzania, combining Maasai Mara, Serengeti, and Ngorongoro with premium accessible accommodations.",
    price: 5800,
    currency: "USD",
    rating: 4.9,
    reviewCount: 0,
    itinerary: "12-day grand accessible safari across Kenya and Tanzania",
    bookingUrl: "https://jaetravel.com/book/east-africa-grand-accessible-safari",
    region: "East Africa",
    country: "Multi-Country",
    metaTitle: "East Africa Grand Accessible Safari | Jae Travel",
    metaDescription: "The ultimate East African accessible safari across Kenya and Tanzania with premium accessible accommodations.",
    keywords: ["East Africa Accessible Safari", "Multi-Country Safari", "Disability Travel"],
    url: "https://jaetravel.com/tours/east-africa-grand-accessible-safari",
  },
]

export default pageKeywords