export interface Tour {
  id: number
  title: string
  destination: string
  duration: string
  price: number
  rating: number
  image: string
  description: string
  category: string
  wildlife: string[]
  slug: string
  currency?: string
}

export const tours: Tour[] = [
    // Kenya Tours
    {
      id: 1,
      title: "Masai Mara JaeTravel Expeditions",
      destination: "Kenya",
      duration: "5 days",
      price: 1200,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/_8502543-1.jpg?updatedAt=1750002814593?height=250&width=350",
      description: "Experience the great migration and witness the Big Five.",
      category: "wildlife",
      wildlife: ["Big Five", "Great Migration", "Lions", "Elephants"],
      slug: "masai-mara-safari-adventure",
    },
    {
      id: 2,
      title: "Amboseli Elephant Safari",
      destination: "Kenya",
      duration: "4 days",
      price: 980,
      rating: 4.7,
      image: "https://ik.imagekit.io/jinx/travel/amboseli-elephants-00007.jpg?updatedAt=1750008046158?height=250&width=350",
      description: "Get close to elephants with Mount Kilimanjaro backdrop.",
      category: "wildlife",
      wildlife: ["Elephants", "Kilimanjaro"],
      slug: "amboseli-elephant-safari",
    },
    {
      id: 3,
      title: "Samburu Game Reserve",
      destination: "Kenya",
      duration: "3 days",
      price: 750,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/Samburu_National_Reserve,_Kenya-26December2012.jpg?updatedAt=1750008245147?height=250&width=350",
      description: "Discover unique wildlife in the northern frontier.",
      category: "wildlife",
      wildlife: ["Giraffes", "Zebras", "Oryx"],
      slug: "samburu-game-reserve",
    },
    {
      id: 4,
      title: "Lake Nakuru Flamingo Tour",
      destination: "Kenya",
      duration: "2 days",
      price: 450,
      rating: 4.5,
      image: "https://ik.imagekit.io/jinx/travel/lake-nakuru-flamingos-in-red-sunset-590x390.jpg?updatedAt=1750008429931?height=250&width=350",
      description: "Witness thousands of flamingos in their natural habitat.",
      category: "photography",
      wildlife: ["Flamingos", "Birds"],
      slug: "lake-nakuru-flamingo-spectacle",
    },
    {
      id: 5,
      title: "Tsavo East & West Safari",
      destination: "Kenya",
      duration: "6 days",
      price: 1350,
      rating: 4.8,
      image: "https://ik.imagekit.io/jinx/travel/tsavo-west-national-park-chyulu-gate.jpg.webp?updatedAt=1750012915321?height=250&width=350",
      description: "Explore Kenya's largest national park.",
      category: "wildlife",
      wildlife: ["Elephants", "Lions", "Rhinos"],
      slug: "tsavo-east-west-adventure",
    },
    {
      id: 6,
      title: "Mombasa Beach & Safari",
      destination: "Kenya",
      duration: "7 days",
      price: 1600,
      rating: 4.7,
      image: "https://ik.imagekit.io/jinx/travel/kenya-beach-safari-prices-jt-safaris-julius-safaris-diani-beach.jpg?updatedAt=1750012979870?height=250&width=350",
      description: "Combine JaeTravel Expeditions with beach relaxation.",
      category: "adventure",
      wildlife: ["Various"],
      slug: "mombasa-coastal-safari",
    },
    {
      id: 7,
      title: "Mount Kenya Climbing",
      destination: "Kenya",
      duration: "5 days",
      price: 1100,
      rating: 4.4,
      image: "https://ik.imagekit.io/jinx/travel/mt-kenya.jpg?updatedAt=1750013071132?height=250&width=350",
      description: "Challenge yourself with Africa's second highest peak.",
      category: "adventure",
      wildlife: [],
      slug: "mount-kenya-climbing-Expeditions",
    },
    {
      id: 8,
      title: "Laikipia Conservancy",
      destination: "Kenya",
      duration: "4 days",
      price: 1250,
      rating: 4.8,
      image: "https://ik.imagekit.io/jinx/travel/lewa-safari-camp---bush-walk.jpg?updatedAt=1750013183762?height=250&width=350",
      description: "Experience conservation in action.",
      category: "conservation",
      wildlife: ["Rhinos", "Elephants"],
      slug: "laikipia-conservancy",
    },
    {
      id: 9,
      title: "Hell's Gate Adventure",
      destination: "Kenya",
      duration: "2 days",
      price: 380,
      rating: 4.3,
      image: "https://ik.imagekit.io/jinx/travel/861661.jpg?updatedAt=1750013290458?height=250&width=350",
      description: "Bike and hike through dramatic landscapes.",
      category: "adventure",
      wildlife: ["Birds"],
      slug: "hell-gate-lake-naivasha-adventure",
    },
    {
      id: 10,
      title: "Maasai Cultural Experience",
      destination: "Kenya",
      duration: "3 days",
      price: 650,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/magestic-maasai-serengeti.jpg?updatedAt=1750013375250?height=250&width=350",
      description: "Immerse yourself in Maasai culture.",
      category: "culture",
      wildlife: [],
      slug: "maasai-cultural-experience",
    },
    {
      id: 11,
      title: "Aberdare National Park",
      destination: "Kenya",
      duration: "3 days",
      price: 720,
      rating: 4.5,
      image: "https://ik.imagekit.io/jinx/travel/Aberdare.jpg?updatedAt=1750013499302?height=250&width=350",
      description: "Mountain forest safari experience.",
      category: "wildlife",
      wildlife: ["Elephants", "Buffaloes"],
      slug: "aberdare-national-park-safari",
    },
    {
      id: 12,
      title: "Diani Beach Safari Combo",
      destination: "Kenya",
      duration: "8 days",
      price: 1800,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/caption-1.jpg?updatedAt=1750013703250?height=250&width=350",
      description: "Ultimate Kenya safari and beach experience.",
      category: "adventure",
      wildlife: ["Various"],
      slug: "diani-beach-safari-combo",
    },
  
    // Tanzania Tours
    {
      id: 13,
      title: "Serengeti Wildlife Safari",
      destination: "Tanzania",
      duration: "7 days",
      price: 1800,
      rating: 4.8,
      image: "https://ik.imagekit.io/jinx/travel/Game-Drive-north-of-Serengeti-National-Park.jpg?updatedAt=1750013774565?height=250&width=350",
      description: "Explore the endless plains of Serengeti.",
      category: "wildlife",
      wildlife: ["Big Five", "Wildebeest Migration"],
      slug: "serengeti-wildlife-safari",
    },
    {
      id: 14,
      title: "Ngorongoro Crater Tour",
      destination: "Tanzania",
      duration: "3 days",
      price: 950,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/Ngorongoro-Crater.jpg?updatedAt=1750013843530?height=250&width=350",
      description: "Visit the world's largest intact caldera.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "ngorongoro-crater-safari",
    },
    {
      id: 15,
      title: "Kilimanjaro Climbing",
      destination: "Tanzania",
      duration: "8 days",
      price: 2200,
      rating: 4.7,
      image: "https://ik.imagekit.io/jinx/travel/kilimanjaro-moutain-climbing.jpg?updatedAt=1750013910253?height=250&width=350",
      description: "Conquer Africa's highest peak.",
      category: "adventure",
      wildlife: [],
      slug: "kilimanjaro-climbing-Expeditions",
    },
    {
      id: 16,
      title: "Tarangire Elephant Safari",
      destination: "Tanzania",
      duration: "4 days",
      price: 1100,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/TA-1.jpg?updatedAt=1750013999268?height=250&width=350",
      description: "See large herds of elephants.",
      category: "wildlife",
      wildlife: ["Elephants"],
      slug: "tarangire-national-park-safari",
    },
    {
      id: 17,
      title: "Lake Manyara Tree Climbing Lions",
      destination: "Tanzania",
      duration: "2 days",
      price: 580,
      rating: 4.4,
      image: "https://ik.imagekit.io/jinx/travel/04tb-treelions1-facebookJumbo-1.jpg?updatedAt=1750014060199?height=250&width=350",
      description: "Witness unique tree-climbing lions.",
      category: "wildlife",
      wildlife: ["Lions"],
      slug: "lake-manyara-national-park-safari",
    },
    {
      id: 18,
      title: "Zanzibar Spice Island",
      destination: "Tanzania",
      duration: "5 days",
      price: 1300,
      rating: 4.8,
      image: "https://ik.imagekit.io/jinx/travel/160829145810-zanzibar-11-rock.jpg?updatedAt=1750014122225?height=250&width=350",
      description: "Explore the spice island paradise.",
      category: "culture",
      wildlife: [],
      slug: "zanzibar-beach-holiday",
    },
    {
      id: 19,
      title: "Ruaha National Park",
      destination: "Tanzania",
      duration: "6 days",
      price: 1450,
      rating: 4.5,
      image: "https://ik.imagekit.io/jinx/travel/baobab-trees-ruaha.jpg?updatedAt=1750014184839?height=250&width=350",
      description: "Tanzania's largest national park.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "ruaha-national-park-safari",
    },
    {
      id: 20,
      title: "Selous Game Reserve",
      destination: "Tanzania",
      duration: "5 days",
      price: 1350,
      rating: 4.7,
      image: "https://ik.imagekit.io/jinx/travel/images%20(1).jpeg?updatedAt=1750014262541?height=250&width=350",
      description: "Africa's largest game reserve.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "selous-game-reserve-safari",
    },
    {
      id: 21,
      title: "Mikumi National Park",
      destination: "Tanzania",
      duration: "3 days",
      price: 750,
      rating: 4.3,
      image: "https://ik.imagekit.io/jinx/travel/M6.jpg?updatedAt=1750014335135?height=250&width=350",
      description: "Accessible wildlife viewing.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "mikumi-national-park",
    },
    {
      id: 22,
      title: "Arusha Cultural Tour",
      destination: "Tanzania",
      duration: "2 days",
      price: 420,
      rating: 4.2,
      image: "https://ik.imagekit.io/jinx/travel/1687776506_755574c936615bdeeefd.webp?updatedAt=1750014412685?height=250&width=350",
      description: "Experience local Tanzanian culture.",
      category: "culture",
      wildlife: [],
      slug: "arusha-cultural-tour",
    },
    {
      id: 23,
      title: "Katavi National Park",
      destination: "Tanzania",
      duration: "4 days",
      price: 1600,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/images%20(2).jpeg?updatedAt=1750014524461?height=250&width=350",
      description: "Remote wilderness experience.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "katavi-national-park-safari",
    },
    {
      id: 24,
      title: "Mahale Chimpanzee Trek",
      destination: "Tanzania",
      duration: "6 days",
      price: 2100,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/c2a4f1d9-5332-42ab-9ad3-31d99823d5a8_5-day-gombe-and-mahale-national-park-chimpanzee-trekking-xlarge.jpg?updatedAt=1750014593270?height=250&width=350",
      description: "Trek with wild chimpanzees.",
      category: "wildlife",
      wildlife: ["Chimpanzees"],
      slug: "mahale-mountains-national-park-chimpanzee-trekking",
    },
    {
      id: 25,
      title: "Pemba Island Diving",
      destination: "Tanzania",
      duration: "4 days",
      price: 980,
      rating: 4.5,
      image: "https://ik.imagekit.io/jinx/travel/pemba-island-Tanzania.webp?updatedAt=1750014959262?height=250&width=350",
      description: "World-class diving experience.",
      category: "adventure",
      wildlife: [],
      slug: "pemba-island-diving",
    },
    {
      id: 26,
      title: "Stone Town Heritage Tour",
      destination: "Tanzania",
      duration: "2 days",
      price: 350,
      rating: 4.4,
      image: "https://ik.imagekit.io/jinx/travel/51.jpg?updatedAt=1750015033324?height=250&width=350",
      description: "Explore UNESCO World Heritage site.",
      category: "culture",
      wildlife: [],
      slug: "stone-town-heritage-tour",
    },
    {
      id: 27,
      title: "Northern Circuit Safari",
      destination: "Tanzania",
      duration: "10 days",
      price: 2800,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/images%20(3).jpeg?updatedAt=1750015098700?height=250&width=350",
      description: "Complete northern Tanzania experience.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "northern-circuit-safari",
    },
  
    // Rwanda Tours
    {
      id: 28,
      title: "Gorilla Trekking Experience",
      destination: "Rwanda",
      duration: "3 days",
      price: 2500,
      rating: 5.0,
      image: "https://ik.imagekit.io/jinx/travel/gorilla-trekking-experience-13.jpg?updatedAt=1750015182565?height=250&width=350",
      description: "Get up close with mountain gorillas.",
      category: "wildlife",
      wildlife: ["Gorillas"],
      slug: "gorilla-trekking-experience",
    },
    {
      id: 29,
      title: "Nyungwe Forest Canopy Walk",
      destination: "Rwanda",
      duration: "2 days",
      price: 450,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/Walk-trail-nyungwe-Usoke-explorers.jpg?updatedAt=1750015272732?height=250&width=350",
      description: "Walk among the treetops.",
      category: "adventure",
      wildlife: ["Birds"],
      slug: "nyungwe-forest-canopy-walk",
    },
    {
      id: 30,
      title: "Lake Kivu Relaxation",
      destination: "Rwanda",
      duration: "3 days",
      price: 380,
      rating: 4.4,
      image: "https://ik.imagekit.io/jinx/travel/images%20(4).jpeg?updatedAt=1750015334762?height=250&width=350",
      description: "Relax by Africa's great lake.",
      category: "adventure",
      wildlife: [],
      slug: "lake-kivu-relaxation",
    },
    {
      id: 31,
      title: "Akagera National Park",
      destination: "Rwanda",
      duration: "2 days",
      price: 520,
      rating: 4.5,
      image: "https://ik.imagekit.io/jinx/travel/Akagera-national-park-1-750x450.jpg?updatedAt=1750015552704?height=250&width=350",
      description: "Rwanda's only savanna park.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "akagera-national-park-safari",
    },
    {
      id: 32,
      title: "Kigali City Tour",
      destination: "Rwanda",
      duration: "1 day",
      price: 150,
      rating: 4.3,
      image: "https://ik.imagekit.io/jinx/travel/25-Top-Attractions-in-Rwanda-2.jpg?updatedAt=1750004163696?height=250&width=350",
      description: "Explore the clean city of Kigali.",
      category: "culture",
      wildlife: [],
      slug: "kigali-city-tour",
    },
    {
      id: 33,
      title: "Golden Monkey Tracking",
      destination: "Rwanda",
      duration: "2 days",
      price: 680,
      rating: 4.7,
      image: "https://ik.imagekit.io/jinx/travel/golden-monkey-trekking.jpg?updatedAt=1750015688667?height=250&width=350",
      description: "Track rare golden monkeys.",
      category: "wildlife",
      wildlife: ["Monkeys"],
      slug: "golden-monkey-tracking",
    },
  
    // Uganda Tours
    {
      id: 34,
      title: "Bwindi Gorilla Trekking",
      destination: "Uganda",
      duration: "4 days",
      price: 2200,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/Magical-encounters-with-the-mountain-gorillas-of-Bwindi.jpg?updatedAt=1750015754767?height=250&width=350",
      description: "Trek mountain gorillas in Bwindi.",
      category: "wildlife",
      wildlife: ["Gorillas"],
      slug: "bwindi-gorilla-trekking",
    },
    {
      id: 35,
      title: "Queen Elizabeth Safari",
      destination: "Uganda",
      duration: "5 days",
      price: 1150,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/fc.jpg?updatedAt=1750015847691?height=250&width=350",
      description: "Diverse wildlife in scenic landscapes.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "queen-elizabeth-national-park-safari",
    },
    {
      id: 36,
      title: "Murchison Falls Adventure",
      destination: "Uganda",
      duration: "4 days",
      price: 980,
      rating: 4.7,
      image: "https://ik.imagekit.io/jinx/travel/10-days-wildlife-safari-and-yoga-adventure.jpg?updatedAt=1750015915152?height=250&width=350",
      description: "Witness the powerful Murchison Falls.",
      category: "adventure",
      wildlife: ["Birds"],
      slug: "murchison-falls-national-park-safari",
    },
    {
      id: 37,
      title: "Kibale Chimpanzee Tracking",
      destination: "Uganda",
      duration: "3 days",
      price: 750,
      rating: 4.5,
      image: "https://ik.imagekit.io/jinx/travel/kibale-national-park-chimpanzees-uganda-590x390.jpg?updatedAt=1750015970496?height=250&width=350",
      description: "Track our closest relatives.",
      category: "wildlife",
      wildlife: ["Chimpanzees"],
      slug: "kibale-national-park-chimpanzee-trekking",
    },
    {
      id: 38,
      title: "Lake Mburo National Park",
      destination: "Uganda",
      duration: "2 days",
      price: 420,
      rating: 4.3,
      image: "https://ik.imagekit.io/jinx/travel/lake-mburo-national-park.jpg?updatedAt=1750016037012?height=250&width=350",
      description: "Compact park with diverse wildlife.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "lake-mburo-national-park-safari",
    },
    {
      id: 39,
      title: "Rwenzori Mountains Hiking",
      destination: "Uganda",
      duration: "7 days",
      price: 1800,
      rating: 4.8,
      image: "https://ik.imagekit.io/jinx/travel/Rwenzori-Mountains-03_1600p.jpg?updatedAt=1750016117660?height=250&width=350",
      description: "Hike the Mountains of the Moon.",
      category: "adventure",
      wildlife: [],
      slug: "rwenzori-mountains-hiking",
    },
    {
      id: 40,
      title: "Jinja White Water Rafting",
      destination: "Uganda",
      duration: "2 days",
      price: 350,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/nile-river-rafting-itanda.jpg?updatedAt=1750016190875?height=250&width=350",
      description: "Adventure at the source of the Nile.",
      category: "adventure",
      wildlife: [],
      slug: "jinja-adventure-tour",
    },
    {
      id: 41,
      title: "Lake Bunyonyi Relaxation",
      destination: "Uganda",
      duration: "3 days",
      price: 450,
      rating: 4.4,
      image: "https://ik.imagekit.io/jinx/travel/lake-bunyonyi-uganda.webp?updatedAt=1750016252501?height=250&width=350",
      description: "Relax by Uganda's deepest lake.",
      category: "relaxation",
      wildlife: [],
      slug: "lake-bunyonyi-relaxation-tour",
    },
    {
      id: 42,
      title: "Ssese Islands Beach Holiday",
      destination: "Uganda",
      duration: "4 days",
      price: 650,
      rating: 4.5,
      image: "https://ik.imagekit.io/jinx/travel/Travel-to-Ssese-islands.jpg?updatedAt=1750016305699?height=250&width=350",
      description: "Beach paradise on Lake Victoria.",
      category: "beach",
      wildlife: [],
      slug: "ssese-islands-beach-holiday",
    },
    {
      id: 43,
      title: "Lake Naivasha Boat Safari",
      destination: "Kenya",
      duration: "1 day",
      price: 150,
      rating: 4.3,
      image: "https://ik.imagekit.io/jinx/travel/flamingos-lakes-great-rift-valley-1.jpg?updatedAt=1750072866145?updatedAt=1750016305699?height=250&width=350",
      description: "Boat safari on freshwater Lake Naivasha with hippos, birds, and Crescent Island walking safari.",
      category: "wildlife",
      wildlife: ["Various"],
      slug: "lake-naivasha-boat-safari",
    },
    {
      id: 44,
      title: "Accessible Kenya Safari Experience for people with disabilities",
      destination: "Kenya",
      duration: "7 days",
      price: 2450,
      rating: 4.8,
      image: "https://ik.imagekit.io/jinx/travel/WhatsApp%20Image%202025-09-01%20at%204.36.05%20PM.jpeg?updatedAt=1756810077465",
      description: "A fully accessible safari experience designed for travelers with mobility challenges, featuring wheelchair-accessible vehicles, accommodations, and tailored wildlife viewing.",
      category: "wildlife",
      wildlife: ["Elephants", "Lions", "Giraffes", "Zebras", "Hippos", "Various Bird Species"],
      slug: "kenya-disability-safari"
    },
    {
      id: 45,
      title: "4-Day Accessible Masai Mara Experience",
      destination: "Kenya",
      duration: "4 days",
      price: 1450,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/63baaaef6b14d.jpg?updatedAt=1756903341232",
      description: "A focused accessible safari in the Masai Mara with wheelchair-adapted vehicles, accessible tented camps, and front-row seats to the Great Migration.",
      category: "wildlife",
      wildlife: ["Lions", "Elephants", "Cheetahs", "Buffalo", "Wildebeest", "Zebras"],
      slug: "accessible-masai-mara-safari"
    },
    {
      id: 46,
      title: "Tanzania Accessible Safari Adventure",
      destination: "Tanzania",
      duration: "8 days",
      price: 2950,
      rating: 4.7,
      image: "https://ik.imagekit.io/jinx/travel/WhatsApp-Image-2025-01-15-at-12.06.45-PM.webp?updatedAt=1756903260238",
      description: "An inclusive journey through Tanzania’s Serengeti and Ngorongoro Crater with adapted safari vehicles, accessible lodges, and unforgettable wildlife encounters.",
      category: "wildlife",
      wildlife: ["Lions", "Leopards", "Elephants", "Wildebeest", "Rhinos", "Flamingos"],
      slug: "tanzania-accessible-safari"
    },
    {
      id: 47,
      title: "Rwanda Accessible Gorilla Experience",
      destination: "Rwanda",
      duration: "5 days",
      price: 3200,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/bisatelodge1.jpg?updatedAt=1756902495617",
      description: "A rare opportunity to experience Rwanda’s mountain gorillas with specially designed accessible trekking routes, adapted viewing platforms, and cultural encounters.",
      category: "wildlife",
      wildlife: ["Mountain Gorillas", "Golden Monkeys", "Various Bird Species"],
      slug: "rwanda-accessible-gorilla-safari"
    },
    {
      id: 48,
      title: "Uganda Accessible Primate Safari",
      destination: "Uganda",
      duration: "6 days",
      price: 2200,
      rating: 4.6,
      image: "https://ik.imagekit.io/jinx/travel/6-days-gorilla-tracking-and-rafting-jinja.jpg?updatedAt=1750083327865",
      description: "An accessible primate-focused safari in Uganda with wheelchair-friendly pathways, adapted chimpanzee and gorilla viewing, and a Kazinga Channel boat safari.",
      category: "wildlife",
      wildlife: ["Chimpanzees", "Gorillas", "Hippos", "Crocodiles", "Birdlife"],
      slug: "uganda-accessible-primate-safari"
    },
    {
      id: 49,
      title: "East Africa Grand Accessible Safari",
      destination: "Multi-Country",
      duration: "12 days",
      price: 5800,
      rating: 4.9,
      image: "https://ik.imagekit.io/jinx/travel/Tineke-in-Kenya.png?updatedAt=1756902738914",
      description: "The ultimate East African accessible safari across Kenya and Tanzania, combining Maasai Mara, Serengeti, and Ngorongoro with premium accessible accommodations.",
      category: "wildlife",
      wildlife: ["Lions", "Leopards", "Elephants", "Zebras", "Wildebeest", "Rhinos"],
      slug: "east-africa-grand-accessible-safari"
    },  
  ]

  export default tours